import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaNeonHttp } from "@prisma/adapter-neon";

console.log("DATABASE_URL:", process.env.DATABASE_URL ? "set" : "NOT SET");

const adapter = new PrismaNeonHttp(process.env.DATABASE_URL!, {});
const prisma = new PrismaClient({ adapter });

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    location: "Mumbai, Maharashtra",
    fees: 220000,
    rating: 4.8,
    overview: "IIT Bombay is one of India's premier engineering institutes, known for its cutting-edge research, excellent faculty, and vibrant campus life. Established in 1958, it has consistently ranked among the top engineering colleges in India and Asia.",
    courses: "B.Tech in Computer Science, Electrical Engineering, Mechanical Engineering, Civil Engineering, Aerospace Engineering, Chemical Engineering, Metallurgical Engineering, Physics, Chemistry, Mathematics",
    placements: "Highest Package: ₹2.4 CPA, Average Package: ₹28 LPA, Top Recruiters: Google, Microsoft, Amazon, McKinsey, Goldman Sachs, Intel",
    established: 1958,
    type: "Public",
    website: "https://www.iitb.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi",
    fees: 210000,
    rating: 4.7,
    overview: "IIT Delhi is a leading technical institute known for its academic excellence and research output. Founded in 1961, it offers a wide range of undergraduate and postgraduate programs with strong industry connections.",
    courses: "B.Tech in Computer Science, Electrical Engineering, Mechanical Engineering, Civil Engineering, Chemical Engineering, Textile Technology, Production Engineering",
    placements: "Highest Package: ₹2.2 CPA, Average Package: ₹26 LPA, Top Recruiters: Microsoft, Google, Amazon, Flipkart, Uber, Adobe",
    established: 1961,
    type: "Public",
    website: "https://www.iitd.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Madras",
    location: "Chennai, Tamil Nadu",
    fees: 200000,
    rating: 4.7,
    overview: "IIT Madras is renowned for its strong engineering programs and research initiatives. The campus is known for its greenery and vibrant student community.",
    courses: "B.Tech in Aerospace, Chemical, Civil, Computer Science, Electrical, Mechanical, Metallurgical, Naval Architecture, Ocean Engineering",
    placements: "Highest Package: ₹2.1 CPA, Average Package: ₹25 LPA, Top Recruiters: Google, Microsoft, Amazon, Qualcomm, Texas Instruments",
    established: 1959,
    type: "Public",
    website: "https://www.iitm.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Kharagpur",
    location: "Kharagpur, West Bengal",
    fees: 195000,
    rating: 4.6,
    overview: "IIT Kharagpur is the oldest IIT, established in 1951. It has the largest campus among all IITs and offers a diverse range of programs.",
    courses: "B.Tech in Aerospace, Agricultural, Biotechnology, Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Mining",
    placements: "Highest Package: ₹2.0 CPA, Average Package: ₹24 LPA, Top Recruiters: Google, Microsoft, Amazon, Bain, BCG, McKinsey",
    established: 1951,
    type: "Public",
    website: "https://www.iitkgp.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Kanpur",
    location: "Kanpur, Uttar Pradesh",
    fees: 195000,
    rating: 4.6,
    overview: "IIT Kanpur is known for its strong focus on research and innovation. It has a sprawling campus and excellent academic infrastructure.",
    courses: "B.Tech in Aerospace, Biological, Chemical, Civil, Computer Science, Electrical, Materials Science, Mechanical, Physics",
    placements: "Highest Package: ₹2.0 CPA, Average Package: ₹23 LPA, Top Recruiters: Google, Amazon, Microsoft, Goldman Sachs, Tower Research",
    established: 1959,
    type: "Public",
    website: "https://www.iitk.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Roorkee",
    location: "Roorkee, Uttarakhand",
    fees: 190000,
    rating: 4.5,
    overview: "IIT Roorkee is one of the oldest engineering institutions in Asia, established in 1847. It has a rich heritage and strong academic traditions.",
    courses: "B.Tech in Architecture, Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Production",
    placements: "Highest Package: ₹1.8 CPA, Average Package: ₹22 LPA, Top Recruiters: Google, Amazon, Microsoft, Samsung, Tata Motors",
    established: 1847,
    type: "Public",
    website: "https://www.iitr.ac.in",
    imageUrl: null,
  },
  {
    name: "National Institute of Technology Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    fees: 140000,
    rating: 4.4,
    overview: "NIT Trichy is consistently ranked among the top NITs in India. It offers high-quality engineering education with excellent placement records.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Electronics, Instrumentation, Mechanical, Metallurgical, Production",
    placements: "Highest Package: ₹1.5 CPA, Average Package: ₹18 LPA, Top Recruiters: Google, Amazon, Microsoft, Intel, Qualcomm",
    established: 1964,
    type: "Public",
    website: "https://www.nitt.edu",
    imageUrl: null,
  },
  {
    name: "National Institute of Technology Surathkal",
    location: "Mangalore, Karnataka",
    fees: 135000,
    rating: 4.3,
    overview: "NIT Surathkal, also known as NITK, is a premier engineering institute located on the coast of Karnataka known for its strong academic programs.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Electronics, Information Technology, Mechanical, Metallurgical, Mining",
    placements: "Highest Package: ₹1.4 CPA, Average Package: ₹17 LPA, Top Recruiters: Amazon, Microsoft, Google, Adobe, Cisco",
    established: 1960,
    type: "Public",
    website: "https://www.nitk.ac.in",
    imageUrl: null,
  },
  {
    name: "Birla Institute of Technology and Science Pilani",
    location: "Pilani, Rajasthan",
    fees: 250000,
    rating: 4.4,
    overview: "BITS Pilani is a premier private engineering institute known for its rigorous academic programs, innovative teaching methods, and strong industry connections.",
    courses: "BE in Chemical, Civil, Computer Science, Electrical, Electronics, Instrumentation, Mechanical, Manufacturing, Pharmacy",
    placements: "Highest Package: ₹1.6 CPA, Average Package: ₹20 LPA, Top Recruiters: Google, Microsoft, Amazon, Goldman Sachs, Texas Instruments",
    established: 1964,
    type: "Private",
    website: "https://www.bits-pilani.ac.in",
    imageUrl: null,
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi",
    fees: 180000,
    rating: 4.2,
    overview: "DTU, formerly Delhi College of Engineering, is one of the oldest engineering colleges in India with a strong reputation for technical education.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biotechnology, Mathematics, Physics",
    placements: "Highest Package: ₹1.2 CPA, Average Package: ₹15 LPA, Top Recruiters: Microsoft, Amazon, Google, Samsung, Uber",
    established: 1941,
    type: "Public",
    website: "https://www.dtu.ac.in",
    imageUrl: null,
  },
  {
    name: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    fees: 195000,
    rating: 4.1,
    overview: "VIT is a leading private engineering institute known for its world-class infrastructure, international collaborations, and strong placement track record.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biotechnology, Information Technology",
    placements: "Highest Package: ₹1.3 CPA, Average Package: ₹12 LPA, Top Recruiters: Amazon, Microsoft, Google, Cognizant, Infosys",
    established: 1984,
    type: "Private",
    website: "https://www.vit.ac.in",
    imageUrl: null,
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal, Karnataka",
    fees: 280000,
    rating: 4.0,
    overview: "MIT Manipal is a premier private engineering institute known for its excellent infrastructure, experienced faculty, and global alumni network.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Aeronautical, Biomedical, Information Technology",
    placements: "Highest Package: ₹1.1 CPA, Average Package: ₹10 LPA, Top Recruiters: Microsoft, Amazon, Google, Deloitte, KPMG",
    established: 1957,
    type: "Private",
    website: "https://www.manipal.edu/mit.html",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Guwahati",
    location: "Guwahati, Assam",
    fees: 195000,
    rating: 4.5,
    overview: "IIT Guwahati is known for its scenic campus on the banks of the Brahmaputra and its strong academic and research programs.",
    courses: "B.Tech in Biotechnology, Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Engineering Physics",
    placements: "Highest Package: ₹1.9 CPA, Average Package: ₹23 LPA, Top Recruiters: Google, Amazon, Microsoft, Qualcomm, Uber",
    established: 1994,
    type: "Public",
    website: "https://www.iitg.ac.in",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Technology Hyderabad",
    location: "Hyderabad, Telangana",
    fees: 200000,
    rating: 4.5,
    overview: "IIT Hyderabad is one of the newer IITs that has rapidly established itself as a center of excellence in engineering and research.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Mechanical, Engineering Science, Materials Science",
    placements: "Highest Package: ₹1.8 CPA, Average Package: ₹22 LPA, Top Recruiters: Google, Microsoft, Amazon, Adobe, Intel",
    established: 2008,
    type: "Public",
    website: "https://www.iith.ac.in",
    imageUrl: null,
  },
  {
    name: "Anna University",
    location: "Chennai, Tamil Nadu",
    fees: 50000,
    rating: 3.9,
    overview: "Anna University is a premier public university offering engineering and technology programs. It has a large network of affiliated colleges across Tamil Nadu.",
    courses: "B.E. in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Production, Instrumentation",
    placements: "Highest Package: ₹40 LPA, Average Package: ₹8 LPA, Top Recruiters: TCS, Infosys, Cognizant, Amazon, Microsoft",
    established: 1978,
    type: "Public",
    website: "https://www.annauniv.edu",
    imageUrl: null,
  },
  {
    name: "Jadavpur University",
    location: "Kolkata, West Bengal",
    fees: 24000,
    rating: 4.0,
    overview: "JU is a prestigious public university known for its engineering and humanities programs. It has a strong research culture and distinguished alumni.",
    courses: "B.E. in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Production, Instrumentation",
    placements: "Highest Package: ₹50 LPA, Average Package: ₹12 LPA, Top Recruiters: Google, Microsoft, Amazon, TCS, PwC",
    established: 1955,
    type: "Public",
    website: "https://www.jaduniv.edu.in",
    imageUrl: null,
  },
  {
    name: "College of Engineering Pune",
    location: "Pune, Maharashtra",
    fees: 80000,
    rating: 4.0,
    overview: "COEP is one of the oldest engineering colleges in India, established in 1854. It has a strong tradition of academic excellence and innovation.",
    courses: "B.Tech in Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Production",
    placements: "Highest Package: ₹45 LPA, Average Package: ₹10 LPA, Top Recruiters: Microsoft, Amazon, Google, Tata Motors, Bajaj Auto",
    established: 1854,
    type: "Public",
    website: "https://www.coep.org.in",
    imageUrl: null,
  },
  {
    name: "PSG College of Technology",
    location: "Coimbatore, Tamil Nadu",
    fees: 85000,
    rating: 4.0,
    overview: "PSG Tech is a highly regarded private engineering college with strong industry partnerships and excellent placement record.",
    courses: "B.E. in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biomedical, Biotechnology",
    placements: "Highest Package: ₹40 LPA, Average Package: ₹9 LPA, Top Recruiters: Amazon, TCS, Cognizant, Ford, Robert Bosch",
    established: 1951,
    type: "Private",
    website: "https://www.psgtech.edu",
    imageUrl: null,
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    location: "Patiala, Punjab",
    fees: 220000,
    rating: 3.9,
    overview: "Thapar Institute is a deemed university known for its engineering programs, research output, and strong industry connections.",
    courses: "B.E. in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biotechnology",
    placements: "Highest Package: ₹1.0 CPA, Average Package: ₹10 LPA, Top Recruiters: Amazon, Microsoft, Google, TCS, Infosys",
    established: 1956,
    type: "Private",
    website: "https://www.thapar.edu",
    imageUrl: null,
  },
  {
    name: "Shiv Nadar University",
    location: "Greater Noida, Uttar Pradesh",
    fees: 350000,
    rating: 3.8,
    overview: "SNU is a private research university offering interdisciplinary programs with a focus on innovation and entrepreneurship.",
    courses: "B.Tech in Computer Science, Electrical, Mechanical, Chemical, Civil, Design",
    placements: "Highest Package: ₹60 LPA, Average Package: ₹12 LPA, Top Recruiters: Microsoft, Amazon, Google, DE Shaw, Samsung",
    established: 2011,
    type: "Private",
    website: "https://www.snu.edu.in",
    imageUrl: null,
  },
  {
    name: "SRM Institute of Science and Technology",
    location: "Chennai, Tamil Nadu",
    fees: 250000,
    rating: 3.7,
    overview: "SRM IST is a large private university with modern infrastructure, diverse programs, and strong international collaborations.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Aerospace, Biomedical",
    placements: "Highest Package: ₹80 LPA, Average Package: ₹8 LPA, Top Recruiters: Amazon, Microsoft, Google, TCS, Infosys",
    established: 1985,
    type: "Private",
    website: "https://www.srmist.edu.in",
    imageUrl: null,
  },
  {
    name: "Lovely Professional University",
    location: "Phagwara, Punjab",
    fees: 180000,
    rating: 3.6,
    overview: "LPU is one of India's largest private universities with modern facilities, diverse programs, and a strong focus on placements.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biotechnology, Aerospace, Food Technology",
    placements: "Highest Package: ₹68 LPA, Average Package: ₹7 LPA, Top Recruiters: Amazon, Microsoft, Google, Cognizant, Infosys",
    established: 2005,
    type: "Private",
    website: "https://www.lpu.in",
    imageUrl: null,
  },
  {
    name: "Amrita Vishwa Vidyapeetham",
    location: "Coimbatore, Tamil Nadu",
    fees: 200000,
    rating: 3.9,
    overview: "Amrita University is a multi-campus private university known for its engineering programs, research initiatives, and holistic education approach.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Aerospace, Biotechnology",
    placements: "Highest Package: ₹50 LPA, Average Package: ₹9 LPA, Top Recruiters: Amazon, Microsoft, Google, TCS, Infosys",
    established: 1994,
    type: "Private",
    website: "https://www.amrita.edu",
    imageUrl: null,
  },
  {
    name: "Indian Institute of Engineering Science and Technology Shibpur",
    location: "Howrah, West Bengal",
    fees: 85000,
    rating: 3.9,
    overview: "IIEST Shibpur is a prestigious public engineering institution with a long history dating back to 1856. It offers diverse engineering programs.",
    courses: "B.Tech in Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Mining, Architecture",
    placements: "Highest Package: ₹35 LPA, Average Package: ₹8 LPA, Top Recruiters: Microsoft, Amazon, TCS, Cognizant, L&T",
    established: 1856,
    type: "Public",
    website: "https://www.iiests.ac.in",
    imageUrl: null,
  },
  {
    name: "Motilal Nehru National Institute of Technology Allahabad",
    location: "Prayagraj, Uttar Pradesh",
    fees: 130000,
    rating: 4.0,
    overview: "MNNIT Allahabad is a premier NIT known for its strong academic programs and excellent placement record.",
    courses: "B.Tech in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Biotechnology",
    placements: "Highest Package: ₹1.2 CPA, Average Package: ₹16 LPA, Top Recruiters: Google, Amazon, Microsoft, Samsung, Intel",
    established: 1961,
    type: "Public",
    website: "https://www.mnnit.ac.in",
    imageUrl: null,
  },
  {
    name: "Visvesvaraya National Institute of Technology Nagpur",
    location: "Nagpur, Maharashtra",
    fees: 130000,
    rating: 4.0,
    overview: "VNIT Nagpur is a premier NIT with excellent academic programs, research facilities, and a strong placement record.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Mining",
    placements: "Highest Package: ₹1.1 CPA, Average Package: ₹15 LPA, Top Recruiters: Amazon, Microsoft, Google, Tata, Mahindra",
    established: 1960,
    type: "Public",
    website: "https://www.vnit.ac.in",
    imageUrl: null,
  },
  {
    name: "National Institute of Technology Warangal",
    location: "Warangal, Telangana",
    fees: 135000,
    rating: 4.3,
    overview: "NIT Warangal is one of the oldest and most prestigious NITs, known for its academic excellence and vibrant campus life.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Biotechnology",
    placements: "Highest Package: ₹1.5 CPA, Average Package: ₹17 LPA, Top Recruiters: Google, Amazon, Microsoft, Qualcomm, Intel",
    established: 1959,
    type: "Public",
    website: "https://www.nitw.ac.in",
    imageUrl: null,
  },
  {
    name: "Sardar Vallabhbhai National Institute of Technology Surat",
    location: "Surat, Gujarat",
    fees: 130000,
    rating: 4.0,
    overview: "SVNIT Surat is a leading NIT with strong engineering programs and good placement opportunities.",
    courses: "B.Tech in Chemical, Civil, Computer Science, Electrical, Electronics, Mechanical, Metallurgical, Textile",
    placements: "Highest Package: ₹1.0 CPA, Average Package: ₹14 LPA, Top Recruiters: Amazon, Microsoft, Google, TCS, L&T",
    established: 1961,
    type: "Public",
    website: "https://www.svnit.ac.in",
    imageUrl: null,
  },
  {
    name: "Maharaja Sayajirao University of Baroda",
    location: "Vadodara, Gujarat",
    fees: 45000,
    rating: 3.6,
    overview: "MSU Baroda is a public university with a strong engineering faculty and diverse academic programs.",
    courses: "B.E. in Computer Science, Electrical, Electronics, Mechanical, Civil, Chemical, Textile",
    placements: "Highest Package: ₹25 LPA, Average Package: ₹6 LPA, Top Recruiters: TCS, Infosys, Cognizant, L&T, Reliance",
    established: 1949,
    type: "Public",
    website: "https://www.msubaroda.ac.in",
    imageUrl: null,
  },
  {
    name: "Veermata Jijabai Technological Institute",
    location: "Mumbai, Maharashtra",
    fees: 80000,
    rating: 4.2,
    overview: "VJTI is a premier government engineering institute in Mumbai, known for its strong academic programs, experienced faculty, and excellent placement record. Established in 1887, it has a rich heritage of producing top engineers.",
    courses: "B.Tech in Computer Science, Electrical Engineering, Mechanical Engineering, Civil Engineering, Electronics, Information Technology, Textile, Production",
    placements: "Highest Package: ₹45 LPA, Average Package: ₹12 LPA, Top Recruiters: Google, Microsoft, Amazon, Tata, L&T",
    established: 1887,
    type: "Public",
    website: "https://www.vjti.ac.in",
    imageUrl: null,
  },
  {
    name: "Institute of Chemical Technology Mumbai",
    location: "Mumbai, Maharashtra",
    fees: 85000,
    rating: 4.5,
    overview: "ICT Mumbai is a premier government deemed university specializing in chemical engineering and technology. It is renowned for its cutting-edge research, excellent faculty, and strong industry connections.",
    courses: "B.Tech in Chemical Engineering, Chemical Technology, Dyestuff Technology, Food Technology, Oil Technology, Pharmacy, Polymer Engineering",
    placements: "Highest Package: ₹60 LPA, Average Package: ₹15 LPA, Top Recruiters: Reliance, Dr. Reddy's, ITC, Unilever, P&G",
    established: 1933,
    type: "Public",
    website: "https://www.ictmumbai.edu.in",
    imageUrl: null,
  },
  {
    name: "Dwarkadas J. Sanghvi College of Engineering",
    location: "Mumbai, Maharashtra",
    fees: 200000,
    rating: 3.9,
    overview: "DJ Sanghvi is a well-regarded private engineering college in Mumbai affiliated with Mumbai University. It offers quality education with modern infrastructure and good placement opportunities.",
    courses: "B.E. in Computer Science, Electronics, Electrical, Mechanical, Civil, Information Technology, Biotechnology",
    placements: "Highest Package: ₹35 LPA, Average Package: ₹8 LPA, Top Recruiters: TCS, Capgemini, JP Morgan, Deloitte, Accenture",
    established: 1994,
    type: "Private",
    website: "https://www.djsanghvi.ac.in",
    imageUrl: null,
  },
  {
    name: "Pune Institute of Computer Technology",
    location: "Pune, Maharashtra",
    fees: 150000,
    rating: 4.0,
    overview: "PICT is a leading private engineering college in Pune known for its strong computer science and IT programs. It has excellent placement records and a vibrant campus culture.",
    courses: "B.E. in Computer Science, Information Technology, Electronics, Electronics & Telecommunications",
    placements: "Highest Package: ₹50 LPA, Average Package: ₹10 LPA, Top Recruiters: Microsoft, Amazon, Goldman Sachs, Google, TCS",
    established: 1983,
    type: "Private",
    website: "https://www.pict.edu",
    imageUrl: null,
  },
  {
    name: "KJ Somaiya College of Engineering",
    location: "Mumbai, Maharashtra",
    fees: 250000,
    rating: 3.8,
    overview: "KJSCE is a respected private engineering college in Mumbai under Somaiya Vidyavihar University. It offers quality engineering education with strong industry linkages and good placements.",
    courses: "B.Tech in Computer Science, Electronics, Electrical, Mechanical, Civil, Information Technology, Artificial Intelligence & Data Science",
    placements: "Highest Package: ₹30 LPA, Average Package: ₹8 LPA, Top Recruiters: Capgemini, Accenture, Wipro, TCS, L&T",
    established: 1983,
    type: "Private",
    website: "https://kjsce.somaiya.edu",
    imageUrl: null,
  },
  {
    name: "MIT World Peace University",
    location: "Pune, Maharashtra",
    fees: 350000,
    rating: 3.7,
    overview: "MIT WPU is a private university in Pune known for its holistic education approach combining technical excellence with value-based learning. It offers modern infrastructure and decent placement opportunities.",
    courses: "B.Tech in Computer Science, Electronics, Mechanical, Civil, Electrical, Chemical, Biotechnology, Data Science",
    placements: "Highest Package: ₹25 LPA, Average Package: ₹7 LPA, Top Recruiters: Cognizant, Tech Mahindra, Infosys, TCS, Wipro",
    established: 1983,
    type: "Private",
    website: "https://www.mitwpu.edu.in",
    imageUrl: null,
  },
];

async function main() {
  console.log("Seeding database...");

  for (const college of colleges) {
    await prisma.college.create({ data: college });
  }

  console.log(`Seeded ${colleges.length} colleges`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
